export const personalInfo = {
  name: "Gerardo Kohatus",
  title: "Full Stack Developer",
  location: "Buenos Aires, Argentina",
  email: "gerardo.kohatus@gmail.com",
  phone: "+54 9 11 3027 8472",
  linkedin: "https://linkedin.com/in/gerardo-kohatus",
  github: "https://github.com/Ger06",
  description: "Con 4 años de experiencia como Full Stack Developer, participé en el desarrollo y mantenimiento de aplicaciones escalables del lado del cliente y del servidor. Me enfoco en optimizar la experiencia de usuario y garantizar la seguridad en el manejo de datos.",
};

export const experiences = [
  {
    title: "Full Stack Developer",
    company: "Grupo Aberasturi",
    period: "Marzo 2026 - Actualidad",
    description: "Plataforma de Remates Ganadero",
    responsibilities: [
      "Sistema de pujas en tiempo real basado en eventos",
      "Servidor de streaming de video propio con WebRTC (MediaSoup + Socket.IO)",
      "Ciclo de vida completo de subastas en PHP/Laravel",
    ],
    technologies: ["Node.js", "WebRTC", "MediaSoup", "Socket.IO", "PHP", "Laravel"],
  },
  {
    title: "Full Stack Developer",
    company: "Freelance",
    period: "Mayo 2025 - Actualidad",
    description: "Proyecto Linea Aérea",
    responsibilities: [
      "Desarrollo de la funcionalidad 'tallaje inteligente' utilizando Java con Spring Boot",
      "Mantenimiento y actualización de base de datos MySQL",
      "Gestión de imágenes en AWS S3",
    ],
    technologies: ["Java", "Spring Boot", "MySQL", "AWS S3"],
  },
  {
    title: "Full Stack Developer",
    company: "Ai Monkey",
    period: "Junio 2022 - Enero 2025",
    description: "Proyecto e-commerce",
    responsibilities: [
      "Desarrollo completo del sistema de tienda online con catálogo, carrito y pagos",
      "Integración de plataformas de pago como Affirm y Authorize",
      "Diseño de UI con React y Next.js, manejo de estado con Redux",
      "Construcción del backend con Node.js y Express",
      "Soporte en despliegue con AWS y Docker",
    ],
    technologies: ["React", "Next.js", "Redux", "Node.js", "Express", "AWS", "Docker"],
  },
  {
    title: "Full Stack Developer",
    company: "Ai Monkey",
    period: "Junio 2022 - Enero 2025",
    description: "App Social",
    responsibilities: [
      "Desarrollo de aplicación para creación y colaboración en recuerdos multimedia",
      "Lógica de manejo de relaciones entre usuarios con roles dinámicos",
      "Backend con Node.js y MongoDB",
      "Sistema de permisos personalizados para control de acceso",
    ],
    technologies: ["Node.js", "MongoDB", "React"],
  },
  {
    title: "Full Stack Developer",
    company: "Ai Monkey",
    period: "Junio 2022 - Enero 2025",
    description: "App Bienestar",
    responsibilities: [
      "Implementación de integraciones backend con NestJS",
      "Decisiones estructurales: modularización y controladores reutilizables",
      "Seguridad de datos sensibles",
    ],
    technologies: ["NestJS", "TypeScript"],
  },
];

export const skills = {
  frontend: [
    { name: "React", icon: "react" },
    { name: "Next.js", icon: "nextjs" },
    { name: "TypeScript", icon: "typescript" },
    { name: "JavaScript", icon: "javascript" },
    { name: "Redux", icon: "redux" },
    { name: "Zustand", icon: "zustand" },
    { name: "React Query", icon: "react-query" },
    { name: "Tailwind CSS", icon: "tailwind" },
    { name: "shadcn/ui", icon: "shadcn" },
    { name: "HTML5", icon: "html5" },
    { name: "CSS3", icon: "css3" },
  ],
  backend: [
    { name: "Node.js", icon: "nodejs" },
    { name: "Express", icon: "express" },
    { name: "NestJS", icon: "nestjs" },
    { name: "Java", icon: "java" },
    { name: "Spring Boot", icon: "spring" },
    { name: "Python", icon: "python" },
    { name: "PHP", icon: "php" },
    { name: "Laravel", icon: "laravel" },
    { name: "Socket.IO", icon: "socketio" },
    { name: "WebRTC", icon: "webrtc" },
  ],
  database: [
    { name: "PostgreSQL", icon: "postgresql" },
    { name: "MySQL", icon: "mysql" },
    { name: "MongoDB", icon: "mongodb" },
    { name: "Supabase", icon: "supabase" },
    { name: "pgvector", icon: "postgresql" },
    { name: "Redis", icon: "redis" },
    { name: "Prisma", icon: "prisma" },
    { name: "Sequelize", icon: "sequelize" },
  ],
  tools: [
    { name: "Git", icon: "git" },
    { name: "Docker", icon: "docker" },
    { name: "AWS (Lambda, S3, EC2)", icon: "aws" },
    { name: "GitHub Actions", icon: "github" },
    { name: "Vitest", icon: "vitest" },
    { name: "Gitflow", icon: "git" },
    { name: "Scrum", icon: "scrum" },
    { name: "Jira", icon: "jira" },
    { name: "Trello", icon: "trello" },
  ],
  ai: [
    { name: "Claude Code", icon: "claude" },
    { name: "Spec-Driven Development", icon: "sdd" },
    { name: "TDD", icon: "tdd" },
    { name: "RAG", icon: "rag" },
    { name: "Embeddings", icon: "embeddings" },
    { name: "LLM Agents", icon: "llm" },
    { name: "Groq", icon: "groq" },
  ],
};

export const projects = [
  {
    title: "Job Search Copilot",
    description: "Copiloto con IA para búsquedas laborales que adapta el CV a cada oferta usando RAG sobre un banco de bullets propio.",
    technologies: ["Next.js", "Express", "TypeScript", "Supabase (pgvector)", "Groq", "Vitest"],
    highlights: [
      "RAG sobre banco de bullets con embeddings y pgvector",
      "Agente de CV con fit score",
      "Importación de CV desde PDF/DOCX",
      "Arquitectura Ports & Adapters con TDD",
    ],
    link: "https://job-search-copilot-frontend.vercel.app",
    github: "https://github.com/Ger06/job-search-copilot",
    period: "2026",
    type: "Personal",
  },
  {
    title: "Training App",
    description: "Aplicación de gestión de entrenamientos para entrenadores y alumnos, con frontend y API en un mismo proyecto Next.js.",
    technologies: ["Next.js 16", "React 19", "TypeScript", "MongoDB", "shadcn/ui", "Vitest"],
    highlights: [
      "Spec-Driven Development + TDD",
      "Dominio desacoplado de React y MongoDB",
      "Auth propia con sesiones y cookies firmadas",
      "Migraciones versionadas con $jsonSchema",
    ],
    github: "https://github.com/Ger06/trainning-app",
    period: "2026",
    type: "Personal",
  },
  {
    title: "Proyecto Inmobiliario",
    description: "Sistema de scraping y procesamiento de datos para propiedades inmobiliarias de múltiples portales, con geolocalización automatizada y base de datos espacial.",
    technologies: ["FastAPI", "PostgreSQL (PostGIS)", "Celery", "Redis", "React"],
    highlights: [
      "Scraping multicanal automático",
      "Geolocalización en mapa interactivo",
      "Manejo de colas con Celery y Redis",
      "Consultas espaciales optimizadas con PostGIS",
    ],
    link: "https://real-estate-investment-theta.vercel.app/",
    github: "https://github.com/Ger06/Real-Estate-Investment",
    period: "2026",
    type: "Personal",
  },
];
